stages:
  - template: azure/stages.yml@templates
  - stage: Release
    dependsOn: test
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
    - job:
      strategy:
        matrix:
          linux:
            imageName: 'ubuntu-16.04'
            target: 'x86_64-unknown-linux-gnu'
            crate_name: cobalt
      pool:
        vmImage: $(imageName)
      steps:
      - template: azure/install-rust.yml@templates
      - script: |
          cargo rustc --target $TARGET --release --bin $CRATE_NAME --features "pagination-unstable"
        displayName: Build
      - task: CopyFiles@2
        displayName: Stage assets
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/target/$(TARGET)/release'
          contents: $(crate_name)
          targetFolder: '$(Build.BinariesDirectory)/'
      - task: ArchiveFiles@2
        displayName: Tarball assets
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)/$(crate_name)'
          archiveType: 'tar'
          tarCompression: 'gz'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(crate_name)-$(Build.SourceBranchName)-$(TARGET).tar.gz'
      - task: GithubRelease@0
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
        inputs:
          gitHubConnection: 'Azure'
          repositoryName: 'Geobert/cobalt.rs'
          action: 'edit'
          target: '$(build.sourceVersion)'
          tagSource: 'manual'
          tag: '$(Build.SourceBranchName)'
          assets: '$(Build.ArtifactStagingDirectory)/$(crate_name)-$(Build.SourceBranchName)-$(TARGET).tar.gz'
          title: '$(Build.SourceBranchName)'
          assetUploadMode: 'replace'
          addChangeLog: true
   
resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: Azure

