stages:
  - stage: Check
    jobs:
    - job: check
      pool:
        vmImage: ubuntu-16.04
      steps:
      - template: azure/install-rust.yml@templates
      - script: cargo check --features "pagination-unstable"
        displayName: Check pagination-unstable
  - stage: Test
    dependsOn: Check
    jobs:
    - job: test
      pool:
        vmImage: ubuntu-16.04
      steps:
      - template: azure/install-rust.yml@templates
      - script: cargo test --features "pagination-unstable"
        displayName: Test pagination-unstable
  - stage: Release
    dependsOn: Test
    condition: succeeded() #startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
    - job:
      pool:
        vmImage: ubuntu-16.04
      steps:
      - template: azure/install-rust.yml@templates
      - script: |
          cargo build --release --features "pagination-unstable"
        displayName: Build
      - task: CopyFiles@2
        displayName: Stage assets
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/target/release'
          contents: cobalt
          targetFolder: '$(Build.BinariesDirectory)/'
      - task: ArchiveFiles@2
        displayName: Tarball assets
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)/cobalt'
          archiveType: 'tar'
          tarCompression: 'gz'
          archiveFile: '$(Build.ArtifactStagingDirectory)/cobalt.rs.tar.gz'
      - task: GithubRelease@0
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
        inputs:
          gitHubConnection: 'Azure'
          repositoryName: 'Geobert/cobalt.rs'
          action: 'edit'
          target: '$(build.sourceVersion)'
          tagSource: 'manual'
          tag: '$(Build.SourceBranchName)'
          assets: '$(Build.ArtifactStagingDirectory)/cobalt.rs.tar.gz'
          title: '$(Build.SourceBranchName)'
          assetUploadMode: 'replace'
          addChangeLog: false
   
resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: Azure

