trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

resources:
  repositories:
    - repository: templates
      type: github
      name: xoac/rust-azure-pipelines
      endpoint: Azure

jobs:
# Check formatting
- template: ci/rustfmt.yml@templates
  parameters:
    name: rustfmt
    displayName: Check formatting

# Cargo check
- template: ci/cargo-check.yml@templates
  parameters:
    name: cargo_check
    displayName: Cargo check

# This represents the minimum Rust version supported.
# Tests are not run as tests may require newer versions of rust.
- template: ci/cargo-check.yml@templates
  parameters:
    name: minrust
    rust_version: 1.32.0 # The 2018 edition
    displayName: Check rust min ver

################
# Test stage   #
###############

# Test stable
- template: ci/test.yml@templates
  parameters:
    dependsOn:
      - cargo_check
    name: cargo_test_stable
    displayName: Cargo test
    cross: true # Test on Windows and macOS

# Test nightly
- template: ci/test.yml@templates
  parameters:
    name: cargo_test_nightly
    displayName: Cargo test
    rust_version: nightly

###################
#    DEPLOY PART  #
###################
# TODO you need to modify git parameters and specify variable in pipeline. See [README.md](https://github.com/xoac/rust-azure-pipelines/blob/master/README.md)

# Release binary
- template: ci/github-release.yml@templates
  parameters:
   name: github_release
   dependsOn:
      - minrust
      - rustfmt
      - cargo_check
      - cargo_test_stable
   rust_version: stable
   condition: succeeded() #and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
   contents: |
     *
     !*.rlib
     !*.d
     !.*
   targets: # TODO specify targets you want to release
    - x86_64-unknown-linux-gnu
   github:
    gitHubConnection: Azure
    repositoryName: Geobert/cobalt.rs
    isPreRelease: true
